language: node_js

node_js:
  - "12"

cache:
    directories:
      - "$HOME/.npm"

matrix:
  fast_finish: true

install:
  - npm ci

stages:
  - Test
  - Build

jobs:
  include:
    - stage: Test
      name: "Linting"
      script: npm run lint
    - stage: Build
      name: "AOT Compiler"
      script: npm run pipeline

