language: node_js

os: linux

node_js:
  - "12"

cache:
  directories:
    - "$HOME/.npm"

stages:
  - compile
  - test

branches:
  except:
  - legacy
  - experimental

env: NODE_ENV=ci

jobs:
  include:
    - stage: compile
      script: npm run pipeline
    - stage: test
      script: npm run lint

