language: node_js

node_js:
  - "12"

cache:
    directories:
      - "$HOME/.npm"

matrix:
  fast_finish: true

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      script: npm run pipeline
    - stage: test
      script: npm run lint

