language: node_js

node_js:
  - "12"

cache:
  npm: true

matrix:
  fast_finish: true

stages:
  - AOT Compilation
  - Build

jobs:
  include:
    - stage: AOT Compilation
      script: npm run aot
    - stage: Build
      script: npm run production

